name: "Ruby on Rails CI"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby with RVM
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install bundler
        run: gem install bundler -v '~> 2.0'

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle update --jobs 4 --retry 3
          bundle update puma

      - name: Set up database schema
        run: bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby with RVM
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install bundler
        run: gem install bundler -v '~> 2.0'

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle update --jobs 4 --retry 3

      - name: Security audit dependencies
        run: bundle exec bundle audit --update

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
